branch-defaults:
  master:
    environment: finalproj
    group_suffix: null
global:
  application_name: finalproj
  branch: null
  default_ec2_keyname: webproj
  default_platform: python2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
