
DB_HOST = "goods4u.ctliigjkgddc.us-west-2.rds.amazonaws.com"
DB_PORT = "3306"
DB_NAME = "XXXXXXX"
DB_USER = "XXXXXXX"
DB_PASS = "XXXXXXXXXXXXXXXXX"

AWS_ACCESS_KEY_ID = "XXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "XXXXXXXXXXXXXXXXXXXXXXXX"
AWS_REGION = "us-west-2"

S3_BUCKET = "finalproj-20170311"
